### ISSUE TITLE
Windows build fails - exceeding bitshifts

### ISSUE THREAD

**Issue by jounathaen** [RWTH-OS/ehyve#2]
This is probably the cause: https://github.com/insula-rs/libwhp/issues/21
Can be mitigated by adding `#[allow(exceeding_bitshifts)]` but I think the mask is still wrong for 64-bit bitfields.

@stlankes why do we use a fork of libwhp at all?

**Comment by stlankes** [comment]
I create a fork to build a valid version of libwhp and afterwards to create PR.

**Comment by jounathaen** [comment]
So we could also use the official version instead?

**Comment by stlankes** [comment]
No, see [PR20](https://github.com/insula-rs/libwhp/pull/20)

**Comment by jounathaen** [comment]
This is now hotfixed. Should be fixed upstream however...

**Comment by stlankes** [comment]
Ah, yes, we could use the upstream version
